- hosts: localhost
  gather_facts: False
  tasks:
     - name: Create pvc
       k8s:
         state: present
         namespace: default
         src: "pvc.yml"
         
     - name: Create deployment
       k8s:
         state: present
         namespace: default
         src: "deployment.yml"
         
     - name: Create service
       k8s:
         state: present
         namespace: default
         src: "service.yml"
